version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: zakosyachnaya/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    image: zakosyachnaya/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: zakosyachnaya/kittygram_gateway
    env_file: .env
    ports:
      - '9000:80'
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
